version: '3'
services:
  app:
    build: ./app
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
    env_file: .env
  nginx:
    image: "nginx"
    ports:
     - "3110:80"
    volumes:
     - ./frontend/html:/usr/share/nginx/html
     - ./frontend/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
     - app
